dist: xenial
language: python
python: "3.6"
cache:
  - pip
before_install:
  - cd lib_py/
  - pwd
install:
  - pip install pipenv
  - pipenv install --dev
  - pip list
  - pipenv graph
  - pwd
before_script:
  - cd ..
script:
  - pytest lib_py/validators.py -sv
