dist: xenial
language: python
python: "3.6"
git:
  depth: 1 # clone only latest revision of repository
cache:
  - pip
before_install:
  - cd lib_py/
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv graph
script:
  - pytest -m schema -v
  - pytest -m relation -v
  - great_expectations validate metadata/answers.csv lib_py/expectations/answers.json
