dist: xenial
language: python
python: "3.6"
git:
  depth: 3
cache:
  - pip
before_install:
  - cd lib_py/
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv graph
before_script:
  - cd ..
script:
  - pwd
  - pytest lib_py/validators.py -sv
